export const numberOfEmpolyees = ['11-20',"50-100","101-1000"]
export const jobLocation = ["onsite" , "remotely" , "hybrid "]
export const workingTime = ["part-time" , "full-time"]
export const seniorityLevel = ["Junior" , "Mid-Level" , "Senior" , "Team-Lead" , "CTO "]
export const technicalSkills= [
    'JavaScript',
    'Python',
    'Java',
    'C#',
    'C++',
    'Ruby',
    'HTML/CSS',
    'SQL',
    'React',
    'Angular',
    'Vue.js',
    'Node.js',
    'Django',
    'Flask',
    'Spring Boot',
    'Kotlin',
    'Swift',
    'Objective-C',
    'PHP',
    'Perl',
    'Go',
    'Rust',
    'TypeScript',
    'MATLAB',
    'R',
    'Scala',
    'Haskell',
    'AWS',
    'Azure',
    'GCP',
    'Docker',
    'Kubernetes',
    'Terraform',
    'Ansible',
    'Jenkins',
    'Git',
    'Linux',
    'Windows Server',
    'Networking',
    'Cybersecurity',
    'Machine Learning',
    'Data Science',
    'Big Data',
    'Blockchain',
    'DevOps',
    'Agile/Scrum',
    'CI/CD',
    'IoT',
    'AR/VR'
]
export const softSkills= [
    'Communication',
    'Teamwork',
    'Problem Solving',
    'Time Management',
    'Adaptability',
    'Critical Thinking',
    'Conflict Resolution',
    'Leadership',
    'Creativity',
    'Work Ethic',
    'Attention to Detail',
    'Interpersonal Skills',
    'Emotional Intelligence',
    'Negotiation',
    'Networking',
    'Public Speaking',
    'Decision Making',
    'Stress Management',
    'Empathy',
    'Patience',
    'Collaboration',
    'Motivation',
    'Active Listening',
    'Flexibility',
    'Dependability',
    'Self-motivation',
    'Open-mindedness',
    'Resilience',
    'Persuasion',
    'Strategic Thinking'
]